In [3]:
import numpy as np
import pandas as pd

1) İndexlerinde "Breaking Bad" , "Chernobyl" , "Leyla ile Mecnun" , "X-Men"  , "Captain America"  , "Disaster Movie" olan 
   Datasında 9.4 , 9.3 , 8.8 , 8.4 , 3.8 , 2.1 olan bir seri oluşturun.(2 Farklı yolla da oluşturun) (Datayı ve İndexleri liste olarak göndererek ve doğrudan dictionary göndererek.)

In [4]:
movie=["Breaking Bad" , "Chernobyl" , "Leyla ile Mecnun" , "X-Men" , "Captain America" , "Disaster Movie"]
rating=[ 9.4 , 9.3 , 8.8 , 8.4 , 3.8 , 2.1]

In [5]:
pd.Series(rating,movie)

Breaking Bad        9.4
Chernobyl           9.3
Leyla ile Mecnun    8.8
X-Men               8.4
Captain America     3.8
Disaster Movie      2.1
dtype: float64

In [6]:
movies={
    "Breaking Bad":9.4,
    "Chernobyl":9.3,
    "Leyla ile Mecnun":8.8,
    "X-Men":8.4,
    "Captain America":3.8,
    "Disaster Movie":2.1
}

In [7]:
pd.Series(movies)

Breaking Bad        9.4
Chernobyl           9.3
Leyla ile Mecnun    8.8
X-Men               8.4
Captain America     3.8
Disaster Movie      2.1
dtype: float64

2) donem1_mat adında bir seri oluşturun. Bu serinin içinde "Ali" ,"Deniz" ,"Aslı" ,"Burak" ,"Kerem" ,"Yasemin" ,"Derya" index değerleri olsun, 
   85, 80 , 94 , 74 , 91 , 96 , 70 data değerleri olsun. Bu şekilde donem1 adında öğrencilerin 1.dönem matematik nor ortalamalarının tutulduğu bir seri oluşturun.

   donem2_mat adında başka bir seri oluşturun. Okula yeni bir öğrenci gelmiş olsun ve indexlerde bu sefer "Ali" ,"Deniz" ,"Aslı" ,"Burak" ,"Kerem" ,"Yasemin" ,"Derya" ,"Mert"         indexleri olsun. 80, 92 , 85 , 87, 90 , 92, 100, 83 ise dataları olsun. Bu iki seriyi birleştirerek bütün öğrencilerin yıl sonu matematik ORTALAMASINI hesaplayın.

   Not : Eğer bir öğrencinin sadece ikinci dönem notu bulunuyorsa, birinci dönem hesaba eklenmeden ikinci dönem notu yıl sonu notu olarak hesaplansın.



In [8]:
donem1_mat={
    "Ali":85,
    "Deniz":80,
    "Aslı":94,
    "Burak":74,
    "Kerem":91,
    "Yasemin":96,
    "Derya":70}

In [9]:
donem1=pd.Series(donem1_mat)
donem1

Ali        85
Deniz      80
Aslı       94
Burak      74
Kerem      91
Yasemin    96
Derya      70
dtype: int64

In [10]:
donem2_mat={
    "Ali":80,
    "Deniz":92,
    "Aslı":85,
    "Burak":87,
    "Kerem":90,
    "Yasemin":92,
    "Derya":100,
    "Mert":83}

In [11]:
donem2=pd.Series(donem2_mat)
donem2

Ali         80
Deniz       92
Aslı        85
Burak       87
Kerem       90
Yasemin     92
Derya      100
Mert        83
dtype: int64

In [17]:
(donem1+donem2)/2


Ali        82.5
Aslı       89.5
Burak      80.5
Deniz      86.0
Derya      85.0
Kerem      90.5
Mert        NaN
Yasemin    94.0
dtype: float64

In [19]:
donem2.add(donem1,fill_value=0)

Ali        165.0
Aslı       179.0
Burak      161.0
Deniz      172.0
Derya      170.0
Kerem      181.0
Mert        83.0
Yasemin    188.0
dtype: float64

3) İndexlerinde "Osman", "Ozlem", "İnci", "Koray", "Melek" olan, columnlarında "Sınıf" , "Cinsiyet" , "Favori Ders" isimlerinde 3 column bulunan bir DF oluşturacaksınız. Osman'ın sınıfı 8 , cinsiyeti "E" , Favori Dersi "Fen"
Ozlem'in sınıfı 11 , cinsiyeti "K" , Favori Dersi "Mat"
İnci'nin sınıfı 5 , cinsiyeti "K" , Favori Dersi "Sosyal"
Koray'ın sınıfı 9 , cinsiyeti "E" , Favori Dersi "Mat"
Meleğin sınıfı 7 , cinsiyeti "K" , Favori Dersi "Ing"          Olacak şekilde bir df oluşturun.

In [20]:
my_index=[ "Osman", "Ozlem", "İnci", "Koray", "Melek" ]
my_column=["Sınıf" , "Cinsiyet" , "Favori Ders"]
my_data=np.array([8,"E","Fen",11,"K","Mat",5,"K","Sosyal",9,"E","Mat",7,"K","Ing"]).reshape(5,3)

In [23]:
df=pd.DataFrame(my_data,my_index,my_column)
df

Sınıf Cinsiyet Favori Ders
Osman     8        E         Fen
Ozlem    11        K         Mat
İnci      5        K      Sosyal
Koray     9        E         Mat
Melek     7        K         Ing

4) GitHubda bulunan "Advertising.csv" reklam datasını herhangi bir platformda DF olarak okuyun ve "df_adv" adında bir değişkene atayın. Ardından df_adv değişkeninin ilk 3 satırına, son 3 satırına , rastgele 3 satırına bakın.

In [24]:
df_adv=pd.read_csv("Advertising.csv")
df_adv

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [25]:
df_adv.head(3)

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3

In [26]:
df_adv.tail(3)

TV  radio  newspaper  sales
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [27]:
df_adv.sample(3)

TV  radio  newspaper  sales
4    180.8   10.8       58.4   12.9
76    27.5    1.6       20.7    6.9
158   11.7   36.9       45.2    7.3

5) Elde ettiğiniz "df_adv" infosuna ve describe'ına bakın ve yorumlamaya çalışın.


In [33]:
df_adv.shape

(200, 4)

In [34]:
df_adv.columns

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [35]:
df_adv.index

RangeIndex(start=0, stop=200, step=1)

In [36]:
df_adv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [37]:
df_adv.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

6) df_adv içinden sadece "TV" sütununu seri olarak çekin.

In [38]:
df_adv[["TV"]]

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

7) df_adv içinden "TV" ve "sales" sütununu çekin ve df_salesTV adında bir değişkene atayın.

In [39]:
df_adv.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [40]:
df_adv["df_salesTV"]=df_adv["TV"]/df_adv["sales"]

In [41]:
df_adv.head()

TV  radio  newspaper  sales  df_salesTV
0  230.1   37.8       69.2   22.1   10.411765
1   44.5   39.3       45.1   10.4    4.278846
2   17.2   45.9       69.3    9.3    1.849462
3  151.5   41.3       58.5   18.5    8.189189
4  180.8   10.8       58.4   12.9   14.015504

8) df_adv içindeki "TV" , "radio" , "newspaper" sütunlarındaki değerleri toplayarak "total_adv" adında yeni bir sütun oluşturun.

In [42]:
df_adv["total_adv"]=df_adv["TV"]+df_adv["radio"]+df_adv["newspaper"]
df_adv

TV  radio  newspaper  sales  df_salesTV  total_adv
0    230.1   37.8       69.2   22.1   10.411765      337.1
1     44.5   39.3       45.1   10.4    4.278846      128.9
2     17.2   45.9       69.3    9.3    1.849462      132.4
3    151.5   41.3       58.5   18.5    8.189189      251.3
4    180.8   10.8       58.4   12.9   14.015504      250.0
..     ...    ...        ...    ...         ...        ...
195   38.2    3.7       13.8    7.6    5.026316       55.7
196   94.2    4.9        8.1    9.7    9.711340      107.2
197  177.0    9.3        6.4   12.8   13.828125      192.7
198  283.6   42.0       66.2   25.5   11.121569      391.8
199  232.1    8.6        8.7   13.4   17.320896      249.4

[200 rows x 6 columns]

9) df_adv içindeki "sales" sütununun drop edilmiş halini ekrana yazdırın. (Kalıcı hale getirmeyin. Sadece ekrana bastırın)

In [43]:
df_adv.drop("sales",axis=1)

TV  radio  newspaper  df_salesTV  total_adv
0    230.1   37.8       69.2   10.411765      337.1
1     44.5   39.3       45.1    4.278846      128.9
2     17.2   45.9       69.3    1.849462      132.4
3    151.5   41.3       58.5    8.189189      251.3
4    180.8   10.8       58.4   14.015504      250.0
..     ...    ...        ...         ...        ...
195   38.2    3.7       13.8    5.026316       55.7
196   94.2    4.9        8.1    9.711340      107.2
197  177.0    9.3        6.4   13.828125      192.7
198  283.6   42.0       66.2   11.121569      391.8
199  232.1    8.6        8.7   17.320896      249.4

[200 rows x 5 columns]

10) df_adv içindeki son 50 index'i(satırı) çekin ve ekrana yazdırın.


In [44]:
df_adv.iloc[-50:]


TV  radio  newspaper  sales  df_salesTV  total_adv
150  280.7   13.9       37.0   16.1   17.434783      331.6
151  121.0    8.4       48.7   11.6   10.431034      178.1
152  197.6   23.3       14.2   16.6   11.903614      235.1
153  171.3   39.7       37.7   19.0    9.015789      248.7
154  187.8   21.1        9.5   15.6   12.038462      218.4
155    4.1   11.6        5.7    3.2    1.281250       21.4
156   93.9   43.5       50.5   15.3    6.137255      187.9
157  149.8    1.3       24.3   10.1   14.831683      175.4
158   11.7   36.9       45.2    7.3    1.602740       93.8
159  131.7   18.4       34.6   12.9   10.209302      184.7
160  172.5   18.1       30.7   14.4   11.979167      221.3
161   85.7   35.8       49.3   13.3    6.443609      170.8
162  188.4   18.1       25.6   14.9   12.644295      232.1
163  163.5   36.8        7.4   18.0    9.083333      207.7
164  117.2   14.7        5.4   11.9    9.848739      137.3
165  234.5    3.4       84.8   11.9   19.705882      322.7
166   17.9   37.6       21.6    8.0    2.237500       77.1
167  206.8    5.2       19.4   12.2   16.950820      231.4
168  215.4   23.6       57.6   17.1   12.596491      296.6
169  284.3   10.6        6.4   15.0   18.953333      301.3
170   50.0   11.6       18.4    8.4    5.952381       80.0
171  164.5   20.9       47.4   14.5   11.344828      232.8
172   19.6   20.1       17.0    7.6    2.578947       56.7
173  168.4    7.1       12.8   11.7   14.393162      188.3
174  222.4    3.4       13.1   11.5   19.339130      238.9
175  276.9   48.9       41.8   27.0   10.255556      367.6
176  248.4   30.2       20.3   20.2   12.297030      298.9
177  170.2    7.8       35.2   11.7   14.547009      213.2
178  276.7    2.3       23.7   11.8   23.449153      302.7
179  165.6   10.0       17.6   12.6   13.142857      193.2
180  156.6    2.6        8.3   10.5   14.914286      167.5
181  218.5    5.4       27.4   12.2   17.909836      251.3
182   56.2    5.7       29.7    8.7    6.459770       91.6
183  287.6   43.0       71.8   26.2   10.977099      402.4
184  253.8   21.3       30.0   17.6   14.420455      305.1
185  205.0   45.1       19.6   22.6    9.070796      269.7
186  139.5    2.1       26.6   10.3   13.543689      168.2
187  191.1   28.7       18.2   17.3   11.046243      238.0
188  286.0   13.9        3.7   15.9   17.987421      303.6
189   18.7   12.1       23.4    6.7    2.791045       54.2
190   39.5   41.1        5.8   10.8    3.657407       86.4
191   75.5   10.8        6.0    9.9    7.626263       92.3
192   17.2    4.1       31.6    5.9    2.915254       52.9
193  166.8   42.0        3.6   19.6    8.510204      212.4
194  149.7   35.6        6.0   17.3    8.653179      191.3
195   38.2    3.7       13.8    7.6    5.026316       55.7
196   94.2    4.9        8.1    9.7    9.711340      107.2
197  177.0    9.3        6.4   12.8   13.828125      192.7
198  283.6   42.0       66.2   25.5   11.121569      391.8
199  232.1    8.6        8.7   13.4   17.320896      249.4

11) df_adv içinde satışları 25'den fazla olanları getirin.

In [50]:
df_adv[df_adv["sales"]>25]

TV  radio  newspaper  sales  df_salesTV  total_adv
36   266.9   43.8        5.0   25.4   10.507874      315.7
98   289.7   42.3       51.2   25.4   11.405512      383.2
147  243.2   49.0       44.3   25.4    9.574803      336.5
175  276.9   48.9       41.8   27.0   10.255556      367.6
183  287.6   43.0       71.8   26.2   10.977099      402.4
198  283.6   42.0       66.2   25.5   11.121569      391.8

12) df_adv içinde "TV" reklamlarına 250'den fazla VE "newspaper" reklamlarına 60'dan fazla harcama yapanları getirin.

In [52]:
df_adv[(df_adv["TV"]>250)&(df_adv["newspaper"]>60)]

TV  radio  newspaper  sales  df_salesTV  total_adv
93   250.9   36.5       72.3   22.2   11.301802      359.7
101  296.4   36.3      100.9   23.8   12.453782      433.6
183  287.6   43.0       71.8   26.2   10.977099      402.4
198  283.6   42.0       66.2   25.5   11.121569      391.8

13) df_adv içinde "newspaper" reklam harcamaları 70'den fazla VEYA "radio" reklam harcamaları 50'den fazla olanları getirin.

In [54]:
df_adv[(df_adv["newspaper"]>70)|(df_adv["radio"]>50)]

TV  radio  newspaper  sales  df_salesTV  total_adv
5      8.7   48.9       75.0    7.2    1.208333      132.6
16    67.8   36.6      114.0   12.5    5.424000      218.4
75    16.9   43.7       89.4    8.7    1.942529      150.0
88    88.3   25.5       73.4   12.9    6.844961      187.2
93   250.9   36.5       72.3   22.2   11.301802      359.7
101  296.4   36.3      100.9   23.8   12.453782      433.6
118  125.7   36.9       79.2   15.9    7.905660      241.8
124  229.5   32.3       74.2   19.7   11.649746      336.0
141  193.7   35.4       75.6   19.2   10.088542      304.7
165  234.5    3.4       84.8   11.9   19.705882      322.7
183  287.6   43.0       71.8   26.2   10.977099      402.4

14) df_adv içinde "sales" ları 10 ile 15(10 ve 15 dahil) arasında olanları getirin.


In [ ]:
df[(df_adv["sales"]>=10)&(df_adv["sales"]<=15)]

TV  radio  newspaper  sales
1     44.5   39.3       45.1   10.4
4    180.8   10.8       58.4   12.9
6     57.5   32.8       23.5   11.8
7    120.2   19.6       11.6   13.2
9    199.8    2.6       21.2   10.6
..     ...    ...        ...    ...
181  218.5    5.4       27.4   12.2
186  139.5    2.1       26.6   10.3
190   39.5   41.1        5.8   10.8
197  177.0    9.3        6.4   12.8
199  232.1    8.6        8.7   13.4

[80 rows x 4 columns]

15) df_adv içinde "sales" ları tam olarak 18.3 veya 14.0 veya 25.5 veya 21.7 veya 13.6 veya 6.9 olanları getirin.

In [ ]:
df[(df_adv["sales"]==18.3)|(df_adv["sales"]==14.0)|(df_adv["sales"]==25.5)|(df_adv["sales"]==21.7)|(df_adv["sales"]==13.6)|(df_adv["sales"]==6.9)]

TV  radio  newspaper  sales
63   102.7   29.6        8.4   14.0
70   199.1   30.6       38.7   18.3
76    27.5    1.6       20.7    6.9
83    68.4   44.5       35.6   13.6
84   213.5   43.0       33.8   21.7
198  283.6   42.0       66.2   25.5

16) GitHubda bulunan "tips.csv" restoran datasını "df_tips" adıyla okuyun. Ardından ilk 5 satırına bakın.

In [68]:
df_tips=pd.read_csv("tips.csv" )
df_tips

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [57]:
df_tips.head(5)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

17) df_tips'in "CC Number" ve "Payment ID" column'larını kalıcı olarak düşürün.

In [70]:
df_tips.drop(["CC Number" , "Payment ID"] , axis=1, inplace = True)
df_tips

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name  
0    Christy Cunningham  
1        Douglas Tucker  
2        Travis Walters  
3      Nathaniel Harris  
4          Tonya Carter  
..                  ...  
239       Michael Avila  
240      Monica Sanders  
241          Keith Wong  
242        Dennis Dixon  
243     Michelle Hardin  

[244 rows x 9 columns]

18) df_tips'in "Payer Name" column'unu kalıcı olarak index yapın ve artık columndan düşürün.

In [71]:
df_tips.set_index("Payer Name",drop=True,inplace=True)


In [72]:
df_tips.head()

total_bill   tip     sex smoker  day    time  size  \
Payer Name                                                               
Christy Cunningham       16.99  1.01  Female     No  Sun  Dinner     2   
Douglas Tucker           10.34  1.66    Male     No  Sun  Dinner     3   
Travis Walters           21.01  3.50    Male     No  Sun  Dinner     3   
Nathaniel Harris         23.68  3.31    Male     No  Sun  Dinner     2   
Tonya Carter             24.59  3.61  Female     No  Sun  Dinner     4   

                    price_per_person  
Payer Name                            
Christy Cunningham              8.49  
Douglas Tucker                  3.45  
Travis Walters                  7.00  
Nathaniel Harris               11.84  
Tonya Carter                    6.15

19) df_tips içindeki kayıtlardan kişi sayısı 4 veya 4'den fazla olan siparişlerin kaç tane olduğunu bulun.(Sorguyu yazıp istediğimiz satırları getirdikten sonra basitçe len() fonksiyonunu kullanarak sayılarını bulabilirsiniz. Veya daha güzeli .shape[0] yaparak elde ettiğiniz sorguda kaç satır olduğunun sayısına ulaşabilirsiniz.)

In [76]:
df_tips[df_tips["size"]>=4].shape[0]

46

20) df_tips içindeki Kişi sayısı 2 ya da 3 olan, sigara içen, erkek olan ve ödediği ücret 20 dolardan az olan kişi sayısını bulalım.

In [87]:
df_tips[((df_tips["smoker"]=="Yes")&(df_tips["sex"]=="Male")&(df_tips["total_bill"]<20))&((df_tips["size"]==2)|(df_tips["size"]==3))]

total_bill   tip   sex smoker   day    time  size  \
Payer Name                                                             
Troy Guerrero           11.24  1.76  Male    Yes   Sat  Dinner     2   
Ryan Hernandez          13.81  2.00  Male    Yes   Sat  Dinner     2   
Joseph Hart             11.02  1.98  Male    Yes   Sat  Dinner     2   
Adam Hall               15.01  2.09  Male    Yes   Sat  Dinner     2   
Mark Smith              17.92  3.08  Male    Yes   Sat  Dinner     2   
Louis Torres            19.44  3.00  Male    Yes  Thur   Lunch     2   
Eric Herrera            12.03  1.50  Male    Yes   Fri  Dinner     2   
David Price             15.36  1.64  Male    Yes   Sat  Dinner     2   
Jason Burgess           16.00  2.00  Male    Yes  Thur   Lunch     2   
David Hall              15.81  3.16  Male    Yes   Sat  Dinner     2   
Larry White              7.25  5.15  Male    Yes   Sun  Dinner     2   
Brian Miles             16.82  4.00  Male    Yes   Sun  Dinner     2   
Walter Simmons          17.89  2.00  Male    Yes   Sun  Dinner     2   
John Dudley             14.48  2.00  Male    Yes   Sun  Dinner     2   
Riley Barnes            15.69  1.50  Male    Yes   Sun  Dinner     2   
Raymond Sullivan        15.48  2.02  Male    Yes  Thur   Lunch     2   
Benjamin Weber          16.58  4.00  Male    Yes  Thur   Lunch     2   
Eric Martin             10.34  2.00  Male    Yes  Thur   Lunch     2   
Joseph Murphy MD        13.51  2.00  Male    Yes  Thur   Lunch     2   
Jason Conrad            18.71  4.00  Male    Yes  Thur   Lunch     3   
Gary Orr                11.59  1.50  Male    Yes   Sat  Dinner     2   
Nicholas Archer          7.74  1.44  Male    Yes   Sat  Dinner     2   
Ricky Johnson           12.16  2.20  Male    Yes   Fri   Lunch     2   
Ronald Vaughn DVM       13.42  1.58  Male    Yes   Fri   Lunch     2   
Jason Parks             15.69  3.00  Male    Yes   Sat  Dinner     3   
Tracy Douglas           15.53  3.00  Male    Yes   Sat  Dinner     2   
Matthew Myers           12.60  1.00  Male    Yes   Sat  Dinner     2   

                   price_per_person  
Payer Name                           
Troy Guerrero                  5.62  
Ryan Hernandez                 6.90  
Joseph Hart                    5.51  
Adam Hall                      7.50  
Mark Smith                     8.96  
Louis Torres                   9.72  
Eric Herrera                   6.02  
David Price                    7.68  
Jason Burgess                  8.00  
David Hall                     7.90  
Larry White                    3.62  
Brian Miles                    8.41  
Walter Simmons                 8.94  
John Dudley                    7.24  
Riley Barnes                   7.84  
Raymond Sullivan               7.74  
Benjamin Weber                 8.29  
Eric Martin                    5.17  
Joseph Murphy MD               6.76  
Jason Conrad                   6.24  
Gary Orr                       5.80  
Nicholas Archer                3.87  
Ricky Johnson                  6.08  
Ronald Vaughn DVM              6.71  
Jason Parks                    5.23  
Tracy Douglas                  7.76  
Matthew Myers                  6.30